---
- hosts: railsapp
  vars:
    ruby_version: 2.4
    postgresql_version: 9.6
    deploy_user: rails
    app_name: SampleApp
    repo_url: git@github.com:nleo/SampleApp.git
    app_path: /home/{{deploy_user}}/{{app_name}}
    database: "{{app_name}}"
    dbuser: "{{app_name}}"
    dbpass: password
    domain: site.example
  remote_user: root
  roles:
    - common
    - ruby
    - postgresql
    - { role: passenger, tags: [ 'passenger' ] }
    # - bash
    # - deploy
    # - ufw
    # - logrotate
