---
- hosts: railsapp
  vars:
    app_name: SampleApp
    domain: site.example
    repo_url: git@github.com:nleo/SampleApp.git
    deploy_user: rails
    app_path: /home/{{deploy_user}}/{{app_name}}
    database: "{{app_name}}"
    dbuser: "{{app_name}}"
    dbpass: password
    ruby_version: 2.4
    postgresql_version: 9.6
  remote_user: root
  roles:
    - { role: common, tags: [ 'common' ] }
    - { role: bash, tags: [ 'bash' ] }
    - { role: ruby, tags: [ 'ruby' ] }
    - { role: postgresql, tags: [ 'postgresql' ] }
    - { role: passenger, tags: [ 'passenger' ] }
    - { role: logrotate, tags: [ 'logrotate' ] }
    - { role: ufw, tags: [ 'ufw' ] }
