# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 28bcd3ed2bc7304a4cf95da60a640fa1ddc09895c5121c9fce12bfc47925d05e4c732db05b5958968b3dd8855822665d5e686ed96d880cd0488c81b01e72f5d8

test:
  secret_key_base: 552c90de7d5ff8fe8fdb644a615b5107268cfe9bd7f0e1914e9a50fdc73ef825e5fbe2871e5d43d4650804b845939b492f4d9dafe4879307923462dd330a21cd

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: 28bcd3ed2bc7304a4cf95da60a640fa1ddc09895c5121c9fce12bfc47925d05e4c732db05b5958968b3dd8855822665d5e686ed96d880cd0488c81b01e72f5d8
