---
- name: Create deploy user
  user:
    name: "{{deploy_user}}"
    shell: /bin/bash
- name: Set hostname
  hostname:
    name: "{{app_name}}"
# - name: Upgrade all packages to the latest version
#   apt:
#     name: "*"
#     state: latest
- name: install packages
  apt: name={{ item }} state=latest
  with_items:
    - libpq-dev
    - python-psycopg2
    - apt-transport-https
    - ca-certificates
  tags:
    - packages
- name: Set authorized key took from file ~/.ssh/id_rsa.pub
  authorized_key:
    user: "{{deploy_user}}"
    state: present
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
