---
- name: Add Phusion Passenger repository
  apt_repository:
    repo: deb https://oss-binaries.phusionpassenger.com/apt/passenger {{ansible_distribution_release}} main
    state: present
- name: Add Phusion Passenger repository key
  apt_key:
    keyserver: hkp://keyserver.ubuntu.com:80
    id: 561F9B9CAC40B2F7
- name: Install Phusion Passenger
  apt:
    name: "{{item}}"
    update_cache: yes
  with_items:
    - nginx-extras
    - passenger
- name: Enable Phusion Passenger
  lineinfile:
    path: /etc/nginx/nginx.conf
    regexp: 'passenger\.conf'
    line: 'include /etc/nginx/passenger.conf;'
- name: env PATH in nginx.conf for nodejs
  lineinfile:
    path: /etc/nginx/nginx.conf
    line: 'env PATH;'
    state: present
    insertbefore: '^user'
- name: Site config
  blockinfile:
    path: /etc/nginx/sites-enabled/{{app_name}}
    block: |
      server {
        server_name {{domain}};
        root {{app_path}}/current/public;
        passenger_enabled on;
        passenger_ruby /usr/bin/ruby;
        passenger_nodejs /usr/bin/nodejs;
        passenger_sticky_sessions on;
      }
    create: yes
- name: Restart nginx
  systemd:
    state: restarted
    daemon_reload: yes
    name: nginx
