---
- name: Add Brightbox ppa
  apt_repository:
    repo: 'ppa:brightbox/ruby-ng'
- name: Install ruby
  apt:
    name: ruby{{ruby_version}}
    update_cache: yes
- name: Install ruby dev
  apt:
    name: ruby{{ruby_version}}-dev
    update_cache: yes
# TODO not work
- name: Install bundler NOT WORK
  gem:
    name: bundler
    state: latest

